config/routes.rb
Rails.application.routes.draw do

  resources :friendships, only: [:destroy]
  get 'friendships', to: 'friendships#index'
  get 'user_friends', to: 'friendships#create'
  get 'friendships/:id', to: 'friendships#destroy'

  resources :user_stocks, only: [:destroy]
  get 'user_stocks', to: 'user_stocks#create'  
  get '/user_stocks/:id', to: 'user_stocks#destroy'
  get 'search_friend', to: 'users#search_friend'

  root 'pages#home'

  resources :users
  get 'signup', to: 'users#new'
  get '/myportfolio', to: 'users#my_portfolio'
  
  get 'signin', to: 'sessions#new'
  post 'signin', to: 'sessions#create'
  get 'signout', to: 'sessions#destroy'
  
  get 'search_stock', to: 'stocks#search'

  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'

  # --------------- Verify if the user can add friends. ------

  def self.check_friendship(user, friend)
    response = where(user_id: user, friend_id: friend).exists?
  end

  def self.delete_friendship(user, friend)
    relation = where(user_id: user, friend_id: friend)
  end

end

app/models/stock.rb
class Stock < ApplicationRecord

    has_many :user_stocks
    has_many :users, through: :user_stocks

    validates :name, :ticker, presence: true

    def self.new_lookup(ticker_symbol)
        client = IEX::Api::Client.new(
            publishable_token: 'Rails.app',
            secret_token: 'Rails.app',
            endpoint: 'https://sandbox.iexapis.com/v1')
        begin
            new(ticker: ticker_symbol, name: client.company(ticker_symbol).company_name, last_price: client.price(ticker_symbol))
        rescue => exception
            return nil
        end
    end

    def self.check_db(ticker_symbol)
        where(ticker: ticker_symbol).first
    end

end

app/models/user.rb
class User < ApplicationRecord
    has_many :user_stocks
    has_many :stocks, through: :user_stocks
    has_many :friendships
    has_many :friends, through: :friendships

    validates :username, presence: true
    validates :password, presence: true
    validates :password_confirmation, presence: true
    has_secure_password

    def stock_already_tracked?(ticker_symbol)
        stock = Stock.check_db(ticker_symbol)
        return false unless stock
        stocks.where(id: stock.id).exists?
    end

    def under_stock_limit?
        stocks.count < 4
    end

    def can_track_stock?(ticker_symbol)
        under_stock_limit? && !stock_already_tracked?(ticker_symbol)
    end

 # ------------------------- Search friend ------------------

    def self.look_friend_up(friend)
        @people = where("username like ?", "%#{friend}%")
        if !(@people.empty?)
            return @people
        else
            return nil
        end
    end
    
end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in?

    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def logged_in?
        !!current_user
    end

    def require_user
        if !(logged_in?)
            redirect_to signin_path, alert: 'You must sign in.'
        end
    end

end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController

  before_action :require_user

  def index
  end

  def create
    # @parameters = Friendship.create(user_id: current_user, friend_id: friend)
    #user = params[:user]
    #friend = params[:friend]
    friendship = Friendship.check_friendship(params[:user], params[:friend])
    if !friendship
      @friendship = Friendship.create(user_id: params[:user], friend_id: params[:friend])
      redirect_to friendships_path, notice: "New friendship added."
    end
  end

  def destroy
    friend = User.find(params[:id])
    friendship = Friendship.where(user_id: current_user, friend_id: friend.id).first
    friendship.destroy
    redirect_to friendships_path, alert: "Friend eliminated."
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
        user = User.new
    end

    def create
        user = User.find_by(username: params[:session][:username])
        if user.present? && user.authenticate(params[:session][:password])
            session[:user_id] = user.id
            redirect_to root_path, notice: "Successfully sign up."
        else
            redirect_to signin_path, alert: "Invalid params. Try again."
        end
    end

    def destroy
        session[:user_id] = nil
        redirect_to signin_path, notice: "Successfully signed out."
    end

end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController

    def search
        if params[:stock].present?
            @stock = Stock.new_lookup(params[:stock])
            if @stock
                @user = current_user
                render 'users/my_portfolio'
            else
                redirect_to myportfolio_path, alert: "You entered an invalid value."
            end
        else
            redirect_to myportfolio_path, alert: "You must enter a value."
        end            
    end
end

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController

    def create
        stock = Stock.check_db(params[:ticker])
        if stock.blank?
            stock = Stock.new_lookup(params[:ticker])
            stock.save
        end
        @user_stock = UserStock.create(user: current_user, stock: stock) 
        redirect_to myportfolio_path, notice: "Object add to your list."
    end

    def destroy
        stock = Stock.find(params[:id])
        user_stock = UserStock.where(user_id: current_user.id, stock_id: stock.id).first
        user_stock.destroy
        redirect_to myportfolio_path, notice: "Stock: #{user_stock.user_id}, #{user_stock.stock_id} was removed from the portfolio."
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :require_user, only: [:my_portfolio]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path, notice: "Login successfully."
      session[:user_id] = @user.id
    else
      render :new, alert: "Invalid params, try again."
    end
  end

  def my_portfolio
    @user = current_user
  end




  def search_friend

    if params[:friend].present?
      @people = User.look_friend_up(params[:friend])
      if @people.nil?
        redirect_to friendships_path, alert: "There's nobody with that username."
      else
        render 'friendships/index'
      end
    else
      redirect_to friendships_path, alert: "You must enter a value."
    end
  end




  private
    def user_params
      params.require(:user).permit(:username, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_stocks_helper.rb
module UserStocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/friendships/_formfriends.html.erb
<h2>Search friends.</h2>
<div>
    <%= form_tag search_friend_path, remote: true, method: :get do %>
        <div class="form-group row">
            <div class="col-sm-9">
                <%= text_field_tag :friend, params[:friend], placeholder: "Search a friend", autofocus: true, class: "form-control form-control-lg" %>
            </div>
            <div class="col-sm-3">
                <%= button_tag type: :submit, class: "btn btn-success" do %>
                    <%= fa_icon 'search 2x' %>
                <% end %>
            </div>
        </div>
    <% end %>
</div>

app/views/friendships/_friendlist.html.erb
<h2>Friends' list.</h2>
<br>
    <div class="col-5">
        <table class="table table-bordered">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">User ID.</th>
                    <th scope="col">Friend</th>
                    <th scope="col">Action</th>
                </tr>
            </thead>
            <tbody>
                <% current_user.friends.each do |friend| %>
                    <tr>
                        <td><%= friend.id %></td>
                        <td><%= friend.username %></td>
                        <td><%= link_to "Remove friend", friendship_path(friend), method: :delete, class: "btn btn-danger" %></td>
                    </tr>
                <% end %>
            </tbody>
        </table>
    </div>

app/views/friendships/_result.html.erb
<h2>Result</h2>
<div class="col-5">
    <table class="table table-bordered">
        <thead class="thead-dark">
            <tr>
                <th scope="col">User ID.</th>
                <th scope="col">Friend</th>
                <th scope="col">Action</th>
            </tr>
        </thead>
        <tbody>
            <% @people.each do |person| %>
            <tr>
                <% if !(current_user.id == person.id) %>
                    <td><%= person.id %></td>
                    <td><%= person.username %></td>
                    <% if !(Friendship.check_friendship(current_user, person)) %>
                        <td><%= link_to "Add friend",  user_friends_path(user: current_user, friend: person.id), method: :post, class: 'btn btn-success' %></td>
                    <% else %>
                        <td><span class="badge badge-secondary">Friend already added.</span></td>
                    <% end %>
                <% end %>
            </tr>
            <% end %>
        </tbody>
    </table>
</div>

app/views/friendships/index.html.erb
<h1>Friends list</h1>
<br><br>
<div>
    <%= render 'friendships/formfriends' %>
</div>
<br>
<% if @people %>
    <%= render 'friendships/result' %>
<% end %>
<br>
<br>
<div>
    <% if current_user.friends.exists? %>
        <div>
            <%= render 'friendships/friendlist' %>
        </div>
    <% else %>
        <p>
            You don't have friends to show.
        </p>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinanceTraker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <header>
    <%= render 'shared/header' %>
  </header>
  <% if notice %>
    <%= render 'shared/notice' %>
  <% elsif %>
    <%= render 'shared/alert' %>
  <% end %>
    <main class="mainClass">
      <%= yield %>
    </main>
    <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Homepage</h1>

app/views/shared/_alert.html.erb
<div>
    <%= alert %>
</div>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Finance app", root_path, class:"nav-link" %>
      </li>
      <li class="nav-item <%= 'active' if request.path == users_path %> ">
        <%= link_to "Users", users_path, class:"nav-link" %>
      </li>
      <% if !logged_in? %>
      <li class="nav-item <%= 'active' if request.path == signin_path %> ">
        <%= link_to "Sign in", signin_path, class:"nav-link" %>
      </li>
      <li class="nav-item <%= 'active' if request.path == signup_path %> ">
        <%= link_to "Sign up", signup_path, class:"nav-link" %>
      </li>
      <% else %>
      <li class="nav-item <%= 'active' if request.path == myportfolio_path %> ">
        <%= link_to "My portfolio", myportfolio_path, class:"nav-link" %>
      </li>
      <li class="nav-item <%= 'active' if request.path == friendships_path %> ">
        <%= link_to "Friend list.", friendships_path, class:"nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Sign out", signout_path, class:"nav-link" %>
      </li>
      <li class="nav-item">
        <span class="nav-link">@<b><%= current_user.username %></b>.</span>
      </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/shared/_notice.html.erb
<div>
    <%= notice %>
</div>

app/views/stocks/_list.html.erb
<% if @user.stocks.present? %>
    <div id="results">
        <div class="row">
            <div class="col-9">
                <table class="table table-bordered table-hover">
                    <thead>
                        <tr>
                            <th scope="col">Ticker</th>
                            <th scope="col">Name</th>
                            <th scope="col">Price</th>
                            <th scope="col">Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        <% @user.stocks.each do |stock| %>
                            <tr>
                                <th scope="row"><%= stock.ticker %></th>
                                <td><%= stock.name %></td>
                                <td><%= stock.last_price %></td>
                                <td><%= link_to 'Remove',  user_stock_path(stock), method: :delete, data: {confirm: 'Are you sure?'}, class:"btn btn-danger" %></td>
                            </tr>
                        <% end %>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
<% else %>
    <p>
        You don't have any stocks to track.
    </p>
<% end %>

app/views/users/_result.html.erb
<% if @stock %>
    <div class="card card-header results-block">
        <b>Symbol: </b><%= @stock.ticker %>
        <b>Company: </b><%= @stock.name %>
        <b>Last price: </b><%= @stock.last_price %>
        <% if current_user.can_track_stock?(@stock.ticker) %>
            <%= link_to 'Add to portfolio', user_stocks_path(user: current_user, ticker: @stock.ticker), class: "btn btn-success", method: :post %>
        <% else %>
            <span class="badge badge-secondary">
                You are already tracking.
                <% if !current_user.under_stock_limit? %>
                    4 stocks.
                <% end %>
                <% if current_user.stock_already_tracked?(@stock.ticker) %>
                    this stock.
                <% end %>
            </span>
        <% end %>
    </div>
<% end %>

app/views/users/index.html.erb
<h1>Users.</h1>
<div>
    <% @users.each do |user| %>
        <br>
            User: <%= user.username %>
        <br>
    <% end %>
</div>

app/views/users/my_portfolio.html.erb
<h1>My Portfolio.</h1>
<div class="search-area">
    <h3>Search stocks.</h3>
    <%= form_tag search_stock_path, remote: true, method: :get do %>
        <div class="form-group row">
            <div class="col-sm-9">
                <%= text_field_tag :stock, params[:stock], placeholder: 'Stock ticker symbol', autofocus: true, class: "form-control form-control-lg" %>
            </div>
            <div class="col-sm-3">
                <%= button_tag type: :submit, class: "btn btn-success" do %>
                    <%= fa_icon 'search 2x' %>
                <% end %>
            </div>
        </div>
    <% end %>
</div>
<br>
<div>
    <%= render 'users/result' %>
</div>
<br>
<div>
    <%= render 'stocks/list' %>
</div>

app/views/users/new.html.erb
<h1>New User</h1>
<%= form_with model: @user do |form| %>
    <div>
        <%= form.label "Username: " %>
        <%= form.text_field :username %>
    </div>
    <div>
        <%= form.label "Password: " %>
        <%= form.password_field :password %>
    </div>
    <div>
        <%= form.label "Password confirmation: " %>
        <%= form.password_field :password_confirmation %>
    </div>
    <div>
        <%= form.submit %>
    </div>
<% end %>